### ISSUE TITLE
laravel8 不支持

### ISSUE THREAD

**Issue by surpaimb** [alphasnow/aliyun-oss-laravel#1]
laravel8.12 不支持,

"alphasnow/aliyun-oss-laravel": "^2.5",

` 
$filename = md5(microtime()) . '.png';
        $rs = Storage::disk('aliyun')->exists('WechatIMG50.png');
`

直接报错
 OSS\Core\OssException 

  :  RequestId:

  at vendor/aliyuncs/oss-sdk-php/src/OSS/Result/Result.php:97
     93▕                 'code' => $code,
     94▕                 'message' => $message,
     95▕                 'body' => $body
     96▕             );
  ➜  97▕             throw new OssException($details);
     98▕         }
     99▕     }
    100▕ 
    101▕     /**

      +5 vendor frames 
  6   app/Console/Commands/TestCommand.php:121
      Illuminate\Filesystem\FilesystemAdapter::exists("WechatIMG50.png")

      +13 vendor frames 
  20  artisan:37
      Illuminate\Foundation\Console\Kernel::handle(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))

**Comment by alphasnow** [comment]
没有复现上述错误,初步判断可能你的配置有问题,可以尝试将以下修改.  
The error was not repeated, May be that you have a configuration problem, Try the following modifications.
```
ALIYUN_OSS_ENDPOINT=<change it to your own oss endpoint>
ALIYUN_OSS_IS_CNAME=false
```
