### ISSUE TITLE
增加 OSS_DOMAIN后上传有问题

### ISSUE THREAD

**Issue by zhanghaidi** [alphasnow/aliyun-oss-laravel#13]
增加 OSS_DOMAIN 前没问题
![image](https://user-images.githubusercontent.com/26913173/159403277-1f8eca48-c6da-4264-9a8b-be37f271e438.png)

增加后
![image](https://user-images.githubusercontent.com/26913173/159403543-13245c36-9be8-4095-9f9c-a73983e2ba4d.png)
上传情况
![image](https://user-images.githubusercontent.com/26913173/159403568-07082e7d-e2d5-4c68-abbf-d41874ade823.png)

**Comment by zhanghaidi** [comment]
增加后并没有上传成功，不知道是哪里出了问题。我是需要域名显示

**Comment by alphasnow** [comment]
检查 OSS_REVERSE_PROXY 是否是 false.
Check whether OSS_REVERSE_PROXY is false

**Comment by zhanghaidi** [comment]
![image](https://user-images.githubusercontent.com/26913173/159417422-10285066-5c74-4cf6-952d-6a5b7f317baf.png)
OSS_REVERSE_PROXY没有配置，默认是false

**Comment by alphasnow** [comment]
> ![image](https://user-images.githubusercontent.com/26913173/159417422-10285066-5c74-4cf6-952d-6a5b7f317baf.png) OSS_REVERSE_PROXY没有配置，默认是false

如果域名是NGINX反向代理的, 需要将OSS_REVERSE_PROXY改为true.
If the domain name is an NGINX reverse proxy, change OSS_REVERSE_PROXY to true.

**Comment by zhanghaidi** [comment]
嗯嗯。好的，多谢，确实如此，问题已解决，另外追问一下，是否支持cdn域名加速？我还未来的及测试

**Comment by alphasnow** [comment]
> 嗯嗯。好的，多谢，确实如此，问题已解决，另外追问一下，是否支持cdn域名加速？我还未来的及测试

支持.
yes.
