### ISSUE TITLE
PHP Fatal error:  Access level to AlphaSnow\AliyunOss\Adapter::getOptionsFromConfig() must be public

### ISSUE THREAD

**Issue by tpid-toto** [alphasnow/aliyun-oss-laravel#14]
i am using Laravel 8.52 with php 8.0. The package I use is alphasnow/aliyun-oss-laravel version 3.0

When I try on tinker with following command
`Storage::put('a.txt', 'Test123')`

got the following error
`PHP Fatal error: Access level to AlphaSnow\AliyunOss\Adapter::getOptionsFromConfig() must be public (as in class AlphaSnow\Flysystem\AliyunOss\AliyunOssAdapter) in /var/www/html/project/vendor/alphasnow/aliyun-oss-laravel/src/Adapter.php on line 31`

**Comment by alphasnow** [comment]
> i am using Laravel 8.52 with php 8.0. The package I use is alphasnow/aliyun-oss-laravel version 3.0
> 
> When I try on tinker with following command `Storage::put('a.txt', 'Test123')`
> 
> got the following error `PHP Fatal error: Access level to AlphaSnow\AliyunOss\Adapter::getOptionsFromConfig() must be public (as in class AlphaSnow\Flysystem\AliyunOss\AliyunOssAdapter) in /var/www/html/project/vendor/alphasnow/aliyun-oss-laravel/src/Adapter.php on line 31`

Please upgrade to version 3.0.2 to fix this issue
