### ISSUE TITLE
Can the client support returning to the oss client?

### ISSUE THREAD

**Issue by jian-kuang** [alphasnow/aliyun-oss-laravel#15]
**Storage::disk("oss")->getAdapter()->client** return oss client？

**Comment by alphasnow** [comment]
yes, like this
`$client = Storage::disk("oss")->getAdapter()->getClient();`

**Comment by jian-kuang** [comment]
dependency **aliyun-oss-flysystem** version is **3.0.x** , getClient method not exists. you need upgrade version

**Comment by jian-kuang** [comment]
dependency **aliyun-oss-flysystem** version is **3.0.x** , getClient method dot not exist.  you need to upgrade version.

**Comment by jian-kuang** [comment]
哈哈，才发现你是国人，我直接指定master分支用了，有时间你可以打个tag

**Comment by alphasnow** [comment]
3.0版本使用`OssClient`, 看这个文档 [README.md](https://github.com/alphasnow/aliyun-oss-laravel/blob/3.x/README.md#use-ossclient)  
version 3.0 uses the `OssClient`, see this documentation [README.md](https://github.com/alphasnow/aliyun-oss-laravel/blob/3.x/README.md#use-ossclient)

**Comment by alphasnow** [comment]
> dependency **aliyun-oss-flysystem** version is **3.0.x** , getClient method dot not exist. you need to upgrade version.

if version is 3.0, you can get it like this.
`$client = Storage::disk("aliyun")->getAdapter()->getClient();`
