### ISSUE TITLE
Type of AlphaSnow\LaravelFilesystem\Aliyun\AliyunAdapter::$config must be array (as in class AlphaSnow\Flysystem\Aliyun\AliyunAdapter)

### ISSUE THREAD

**Issue by mofashi998** [alphasnow/aliyun-oss-laravel#16]
Type of AlphaSnow\LaravelFilesystem\Aliyun\AliyunAdapter::$config must be array (as in class AlphaSnow\Flysystem\Aliyun\AliyunAdapter)

**Comment by mofashi998** [comment]
4.1.0

**Comment by mofashi998** [comment]
4.1.0

**Comment by mofashi998** [comment]
4.1.0  php8

**Comment by Snuffel233** [comment]
尝试把"alphasnow/aliyun-oss-laravel"的版本更换到4.2
建议使用composer官方源同步，部分国内镜像未更新

**Comment by Snuffel233** [comment]
```
composer config -g repo.packagist composer https://repo.packagist.org
composer require alphasnow/aliyun-oss-laravel "^4.2"
```

**Comment by alphasnow** [comment]
> ```
> composer config -g repo.packagist composer https://repo.packagist.org
> composer require alphasnow/aliyun-oss-laravel "^4.2"
> ```

good
