### ISSUE TITLE
不兼容laravel9版本

### ISSUE THREAD

**Issue by pangxianfei** [alphasnow/aliyun-oss-laravel#17]
![图片](https://user-images.githubusercontent.com/9346931/168236772-996dd2ee-388a-4bb8-8f11-f2929bb8b6c1.png)

**Comment by alphasnow** [comment]
> ![图片](https://user-images.githubusercontent.com/9346931/168236772-996dd2ee-388a-4bb8-8f11-f2929bb8b6c1.png)

根据错误提示看到，`flysystem`被`composer.lock`限制在`1.1.9`版本，所以无法完成安装。
建议尝试删除`composer.lock`，再进行安装。

`flysystem` is limited to `1.1.9` by 'composer. lock', try deleting `composer.lock` and installing again.
