### ISSUE TITLE
root参数无效

### ISSUE THREAD

**Issue by williamqian** [alphasnow/aliyun-oss-laravel#18]
![image](https://user-images.githubusercontent.com/19399075/189787189-742d1adc-dc26-461e-90f8-5888123d6617.png)

**Comment by alphasnow** [comment]
> ![image](https://user-images.githubusercontent.com/19399075/189787189-742d1adc-dc26-461e-90f8-5888123d6617.png)

并没有`root`这个参数,如果需要路径前缀使用`prefix`.
There is no 'root' parameter. If you want a path prefix, use 'prefix'.
