### ISSUE TITLE
php8 报错了复现了这个issue的问题

### ISSUE THREAD

**Issue by toknT** [alphasnow/aliyun-oss-laravel#2]
没有复现上述错误,初步判断可能你的配置有问题,可以尝试将以下修改.  
The error was not repeated, May be that you have a configuration problem, Try the following modifications.
```
ALIYUN_OSS_ENDPOINT=<change it to your own oss endpoint>
ALIYUN_OSS_IS_CNAME=false
```

_Originally posted by @alphasnow in https://github.com/alphasnow/aliyun-oss-laravel/issues/1#issuecomment-817454574_

**Comment by alphasnow** [comment]
因本扩展包基于 `aliyuncs/oss-sdk-php`, 依赖包出现的问题, 本扩展也会出现.   
问题源于PHP8对`is_source`函数的更新,具体参考 [https://php.watch/versions/8.0/resource-CurlHandle](https://php.watch/versions/8.0/resource-CurlHandle)  
等待`aliyuncs/oss-sdk-php`更新后, 本扩展将同步更新.

**Comment by toknT** [comment]
抱歉想了想不该开issue的应该在老的下面加下评论,找了一圈laravel+oss发现是php8问题😅
