### ISSUE TITLE
When there is a prefix, the path is spliced ​​2 times

### ISSUE THREAD

**Issue by Jinmei-zh** [alphasnow/aliyun-oss-laravel#21]
## 运行环境 / Runtime environment

* php: 8.0.2
* laravel: 9.19
* aliyun-oss-laravel: 4.6

## 描述问题 / Describe the bug

The url method returns the prefix twice

```php
   # prefix=test
    $disk = Storage::disk('oss');
    $filePath = "20221114/1.jpg";
    return $disk->url($filePath);  # return http://{url}/test/test/20221114/1.jpg
```

**Comment by alphasnow** [comment]
Thanks for submitting the issue.
Issue is fixed, You can update the dependency package, Use the following command.
`composer require alphasnow/aliyun-oss-laravel:4.7`
@Jinmei-zh 
The cause of issue is Laravel update. [laravel#44330](https://github.com/laravel/framework/pull/44330)

**Comment by alphasnow** [comment]
The Ali composer mirror is faulty, you need to use the official mirror.
Execute the following command.
```
composer config -g --unset repos.packagist
```
@Jinmei-zh
