### ISSUE TITLE
是否可以移除 laravel 版本的依赖

### ISSUE THREAD

**Issue by krissss** [alphasnow/aliyun-oss-laravel#22]
## 运行环境 / Runtime environment

* php: 8
* laravel: 9
* aliyun-oss-laravel: 4.x

## 描述问题 / Describe the bug

4.x 增加了对 laravel framework 的依赖，是否可以移除，或者仅依赖 `illuminate/filesystem:^9.0`
这样在非完整的 laravel 项目下也可以直接依赖这个包，而非 `alphasnow/aliyun-oss-flysystem`

**Comment by alphasnow** [comment]
可以,谢谢建议.
增加`laravel framework`的依赖,有些欠缺考虑.
4.7.1版本将会去除`laravel framework`依赖.

Yes, thanks for the suggestion.
Increased dependency on the 'laravel framework', somewhat poorly thought out.
Version 4.7.1 will remove the laravel framework dependency.

**Comment by alphasnow** [comment]
> ## 运行环境 / Runtime environment
> * php: 8
> * laravel: 9
> * aliyun-oss-laravel: 4.x
> 
> ## 描述问题 / Describe the bug
> 4.x 增加了对 laravel framework 的依赖，是否可以移除，或者仅依赖 `illuminate/filesystem:^9.0` 这样在非完整的 laravel 项目下也可以直接依赖这个包，而非 `alphasnow/aliyun-oss-flysystem`

可以,谢谢建议.
增加`laravel framework`的依赖,有些欠缺考虑.
4.7.1版本将会去除`laravel framework`依赖.

Yes, thanks for the suggestion.
Increased dependency on the 'laravel framework', somewhat poorly thought out.
Version 4.7.1 will remove the laravel framework dependency.

**Comment by krissss** [comment]
tks
