### ISSUE TITLE
The upload does not work

### ISSUE THREAD

**Issue by jeanali** [alphasnow/aliyun-oss-laravel#23]
* php: 8.1
* laravel: 9
* aliyun-oss-laravel: 4.7

I create a user that has `full OSS` permission 

I create a bucket read/write 

I install your pkg and put all credentials in .env
```
OSS_ACCESS_KEY_ID=LTAI5t7LT1XXXXXX
OSS_SECRET_ACCESS_KEY=902sCyeJgQXXXXXXXX
OSS_BUCKET=XXXX
OSS_ENDPOINT=https://XXXXXaliyuncs.com
```

I use this code too upload a test file:

```
Route::get('oss', function () {
    dd(Storage::disk('oss')->put('test.txt', 'Hello World'));
});
```

I got a `false` in response! 

Am I missing something?

**Comment by alphasnow** [comment]
Modify the oss configuration file and add `"throw" => true`.
Just like this.
```php
return [
    // ...
    "disks" => [
        // ...
        "oss" => [
            "driver" => "oss",
            "throw" => true,
            // ...
        ]
    ]
];
```
Try it again, you can see the exception information.
