### ISSUE TITLE
Driver [oss] is not supported

### ISSUE THREAD

**Issue by I2C-RoyYou** [alphasnow/aliyun-oss-laravel#31]
## 运行环境 / Runtime environment

* php: 7.4.33
* laravel: 8.12
* aliyun-oss-laravel: 3.3

## 描述问题 / Describe the bug

composer require 跟 install 後, 要使用時出現 Driver [oss] is not supported. 

在 app.php 的 providers 加上 AlphaSnow\LaravelFilesystem\Aliyun\AliyunServiceProvider::class 會出錯,找不到此檔案
改成加上 AlphaSnow\AliyunOss\ServiceProvider::class 一樣出現  Driver [oss] is not supported.

**Comment by alphasnow** [comment]
對於`aliyun-oss-larave:^3.0`,`driver`應該使用`aliyun`.
其他說明參考3.0文檔[README](https://github.com/alphasnow/aliyun-oss-laravel/blob/3.x/README.md)

**Comment by I2C-RoyYou** [comment]
我切換成aliyun後不會跳出錯誤了 但遠端也看不到我傳上去的檔案 .
我是用 $request->file('file') 接回來的檔案陣列
然後陣列解開來後上傳 不會跳錯誤 在oss上也沒看到我的檔案
for($f=0;$f<count($files);$f++) 
{
    $file = $files[$f];
    Storage::disk("aliyun")->put('file/abc.jpg', $file);
}

請問是我哪邊寫錯了嗎？

**Comment by I2C-RoyYou** [comment]
感謝你的幫忙 已成功上傳 謝謝！
