### ISSUE TITLE
OSS_DOMAIN

### ISSUE THREAD

**Issue by purnada** [alphasnow/aliyun-oss-laravel#32]
When we add the OSS_DOMAIN=mybucketdomain.com

when i use Storage::exists(filename.jpg)
it will give error **Unable to check existence for:** filename.jpg. RequestCoreException: cURL error: Could not resolve host: bucketname.mybucketdomain.com (6)

**Comment by alphasnow** [comment]
After configuring `OSS_DOMAIN`, configure `OSS_CNAME`.
Example:
```
OSS_DOMAIN=domain.com
OSS_CNAME=true
```

**Comment by alphasnow** [comment]
If your version is earlier than 4.7.2, you can also try configuring `OSS_REVERSE_PROXY`.
For example:
```
OSS_DOMAIN=domain.com
OSS_REVERSE_PROXY=true
```

If your version is greater than 4.7.2, you don't need to configure `OSS_REVERSE_PROXY`.
