### ISSUE TITLE
前端直传

### ISSUE THREAD

**Issue by toplyb** [alphasnow/aliyun-oss-laravel#4]
您好, 请问有前端直传的相关配置吗

**Comment by alphasnow** [comment]
Not yet, we will consider adding it later
暂时没有,后期会考虑添加.

**Comment by alphasnow** [comment]
I suggest using [ali-oss](https://github.com/ali-sdk/ali-oss) for browser upload,
and using `alibabacloud/sts` for temporary authorization of [ali-oss](https://github.com/ali-sdk/ali-oss).

建议使用 [ali-oss](https://github.com/ali-sdk/ali-oss) 来做浏览器直传,
并且使用 `alibabacloud/sts` 来完成对 [ali-oss](https://github.com/ali-sdk/ali-oss) 的临时授权.
